#!/bin/bash
lock() {
  exec ~/.config/i3/i3lock-multimonitor/lock -i ~/dotfiles/Pictures/wallpaper.png
}

# with openrc use loginctl
[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

case "$1" in
	lock)
		lock
		;;
	logout)
		i3-msg exit
		;;
	suspend)
		i3lock -c 000000 && $logind suspend
		;;
	hibernate)
		i3lock -c 000000 && $logind hibernate
		;;
	reboot)
		$logind reboot
		;;
	shutdown)
		$logind poweroff
		;;
	*)
  echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
  exit 2
esac

exit 0
