#!/usr/bin/env bash

count_monitors() {
  NUMBER_OF_MONITORS=$(xrandr -q | grep -i " connected" | awk 'END {print NR}')
}

get_monitors() {
  MONITOR_LIST=($(xrandr -q | grep -i "connected" | awk 'FNR<=2{print $1}'))
}

get_sys_vendor_name() {
  SYS_VENDOR=$(cat /sys/devices/virtual/dmi/id/sys_vendor)
}
